version: '3.4'
services:
  logicmodulecar:
    image: "dataclaydemo/dataclay-logicmodule"
    container_name: car-logicmodule
    command: "${COMMAND_OPTS}"
    ports:
      - "21034:21034"
    environment:
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmodulecar
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/loggging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
              
  dsjavacar:
    image: "dataclaydemo/dataclay-dsjava"
    command: "${COMMAND_OPTS}"
    ports:
      - "3127:3127"
    depends_on:
      - logicmodulecar
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=3127
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmodulecar
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspythoncar:
    image: "dataclaydemo/dataclay-dspython"
    command: "${COMMAND_OPTS}"
    ports:
      - "7878:7878"
    depends_on:
      - logicmodulecar
      - dsjavacar
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmodulecar
      - DEBUG=True
      - DATASERVICE_PYTHON_PORT_TCP=7878
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
networks:
  default:
    external:
      name: dataclaynetwork