version: '3.4'
services:
  logicmodule:
    image: "bscdataclay/logicmodule:2.0"
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - ./prop/global.properties:/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/dataclay/logging/log4j2.xml:ro
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/dataclay/health/health_check.sh"]
       
  dsjava:
    image: "bscdataclay/dsjava:2.0"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodule
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
    volumes:
      - ./prop/global.properties:/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/dataclay/logging/log4j2.xml:ro
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/dataclay/health/health_check.sh"]
 