version: '3.4'
services:
  logicmodule1:
    image: "bscdataclay/logicmodule:${DATACLAY_JAVA_CONTAINER_VERSION}"
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule1
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro
    healthcheck:
      start_period: 30s
      retries: 5
      test: ["CMD-SHELL", "health_check/logicmodule_health_check.sh"]
            
  ds1java1:
    image: "bscdataclay/dsjava:${DATACLAY_JAVA_CONTAINER_VERSION}"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodule1
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro
    healthcheck:
      start_period: 30s
      retries: 5
      test: ["CMD-SHELL", "health_check/dataservice_health_check.sh"]
