version: '3.5'

volumes:
  dataclay-certs:
    driver: local

services:

  certificates_initializer:
    image: "dataclaydemos/certificate-initializer"
    build:
      context: .
      dockerfile: cert.Dockerfile
    environment:
      - CERTIFICATE_AUTHORITY_HOST=${CERTIFICATE_AUTHORITY_HOST}
    volumes:
      - dataclay-certs:/ssl/:rw
    healthcheck:
      test: bash -c "[ -f /ssl/dataclay-agent.crt ]"
      timeout: 1s
      retries: 20

  proxy:
    image: traefik:v1.7.17
    depends_on:
      - certificates_initializer
    restart: unless-stopped
    command: --docker --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/dataclay/traefik.toml:/traefik.toml
      - dataclay-certs:/ssl:ro
    ports:
      - "80:80"
      - "443:443"

  logicmodule:
    image: "bscdataclay/logicmodule:2.6.jdk11.dev-alpine"
    depends_on:
      - proxy
    environment:
      - LOGICMODULE_HOST=logicmodule
      - LOGICMODULE_PORT_TCP=11034
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - SSL_CLIENT_TRUSTED_CERTIFICATES=/ssl/dataclay-ca.crt
      - SSL_CLIENT_CERTIFICATE=/ssl/dataclay-agent.crt
      - SSL_CLIENT_KEY=/ssl/dataclay-agent.pem
      - SSL_TARGET_LM_ALIAS=11034
      - EXPOSED_IP_FOR_CLIENT=$EXPOSED_IP_FOR_CLIENT
    volumes:
      - dataclay-certs:/ssl/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=logicmodule"
      - "traefik.frontend.rule=Headers: service-alias,11034"
      - "traefik.port=11034"
      - "traefik.protocol=h2c"
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dsjava:
    image: "bscdataclay/dsjava:2.6.jdk11.dev-alpine"
    depends_on:
      - logicmodule
      - proxy
    environment:
      - DATASERVICE_HOST=$EXPOSED_IP_FOR_CLIENT
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=proxy
      - SSL_CLIENT_TRUSTED_CERTIFICATES=/ssl/dataclay-ca.crt
      - SSL_CLIENT_CERTIFICATE=/ssl/dataclay-agent.crt
      - SSL_CLIENT_KEY=/ssl/dataclay-agent.pem
      - SSL_TARGET_LM_ALIAS=11034
    volumes:
      - dataclay-certs:/ssl/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dsjava"
      - "traefik.frontend.rule=Headers: service-alias,2127"
      - "traefik.port=2127"
      - "traefik.protocol=h2c"
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dspython:
    image: "bscdataclay/dspython:2.6.py37.dev-alpine"
    command: "--debug"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_HOST=$EXPOSED_IP_FOR_CLIENT
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=proxy
      - DATASERVICE_PYTHON_PORT_TCP=6867
      - SSL_CLIENT_TRUSTED_CERTIFICATES=/ssl/dataclay-ca.crt
      - SSL_CLIENT_CERTIFICATE=/ssl/dataclay-agent.crt
      - SSL_CLIENT_KEY=/ssl/dataclay-agent.pem
      - SSL_TARGET_LM_ALIAS=11034
    volumes:
      - dataclay-certs:/ssl/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dspython"
      - "traefik.frontend.rule=Headers: service-alias,6867"
      - "traefik.port=6867"
      - "traefik.protocol=h2c"
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
           