version: '3.4'

services:

  logicmodule:
    image: "bscdataclay/logicmodule:develop-slim:develop-alpine:develop-alpine"
    command: "--debug"
    ports:
      - "11034:11034"
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=${LOGICMODULE_HOST}
      - EXPOSED_IP_FOR_CLIENT=${EXPOSED_IP_FOR_CLIENT}
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dsjava:
    image: "bscdataclay/dsjava:develop-slim:develop-alpine:develop-alpine"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodule
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dspython:
    image: "bscdataclay/dspython:develop-slim:develop-alpine:develop-alpine"
    command: "--debug"
    ports:
      - "6867:6867"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
