version: '3.4'
services:
  logicmodulefermata:
    image: "bscdataclay/logicmodule:develop-alpine"
    command: "${COMMAND_OPTS}"
    container_name: fermata-logicmodule
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulefermata
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
              
  dsjavafermata:
    image: "bscdataclay/dsjava:develop-alpine"
    command: "${COMMAND_OPTS}"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodulefermata
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulefermata
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspythonfermata:
    image: "bscdataclay/dspython:develop-alpine"
    command: "${COMMAND_OPTS}"
    depends_on:
      - logicmodulefermata
      - dsjavafermata
    ports:
      - "6867:6867"
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulefermata
      - DATASERVICE_PYTHON_PORT_TCP=6867
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
networks:
  default:
    external:
      name: dataclaynetwork