version: '3.4'

services:

  proxy:
    image: traefik:v1.7.17
    restart: unless-stopped
    command: --docker --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/common/dataclay/traefik.toml:/traefik.toml
      - /home/docker/certs:/ssl:ro
    ports:
      - "80:80"
      - "443:443"
           
  logicmodule:
    image: "dataclaydemo/dataclay-logicmodule"
    depends_on:
      - proxy
    environment:
      - LOGICMODULE_HOST=logicmodule
      - LOGICMODULE_PORT_TCP=11034
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - /home/docker/common/dataclay/prop/global.secure.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - /home/docker/common/dataclay/prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
      - /home/docker/certs:/ssl/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=logicmodule"
      - "traefik.frontend.rule=Headers: service-alias,logicmodule"
      - "traefik.port=11034"
      - "traefik.protocol=h2c"
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
           
  dsjava:
    image: "dataclaydemo/dataclay-dsjava"
    depends_on:
      - logicmodule
      - proxy
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
    volumes:
      - /home/docker/common/dataclay/prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - /home/docker/common/dataclay/prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspython:
    image: "dataclaydemo/dataclay-dspython"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - DEBUG=True
    volumes:
      - /home/docker/common/dataclay/prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - /home/docker/common/dataclay/prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
           