version: '3.4'
services:
  logicmoduletram:
    image: "bscdataclay/logicmodule-alpine"
    container_name: tram-logicmodule
    command: "${COMMAND_OPTS}"
    ports:
      - "21034:21034"
    environment:
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmoduletram
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
              
  dsjavatram:
    image: "bscdataclay/dsjava-alpine"
    command: "${COMMAND_OPTS}"
    ports:
      - "3127:3127"
    depends_on:
      - logicmoduletram
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=3127
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmoduletram
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspythontram:
    image: "bscdataclay/dspython-alpine"
    command: "${COMMAND_OPTS}"
    ports:
      - "7878:7878"
    depends_on:
      - logicmoduletram
      - dsjavatram
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=21034
      - LOGICMODULE_HOST=logicmoduletram
      - DATASERVICE_PYTHON_PORT_TCP=7878
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
networks:
  default:
    external:
      name: dataclaynetwork