version: '3.4'
services:
  logicmodulecity:
    image: "dataclaydemo/dataclay-logicmodule"
    command: "${COMMAND_OPTS}"
    container_name: city-logicmodule
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulecity
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/loggging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
              
  dsjavacity:
    image: "dataclaydemo/dataclay-dsjava"
    command: "${COMMAND_OPTS}"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodulecity
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulecity
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspythoncity:
    image: "dataclaydemo/dataclay-dspython"
    command: "${COMMAND_OPTS}"
    depends_on:
      - logicmodulecity
      - dsjavacity
    ports:
      - "6867:6867"
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodulecity
      - DEBUG=True
      - DATASERVICE_PYTHON_PORT_TCP=6867
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
networks:
  default:
    external:
      name: dataclaynetwork